# Generated by Django 4.0.1 on 2022-03-17 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='birtg_Date',
            new_name='birth_date',
        ),
    ]
